- Type: Training
  Trainers:
    - Name: Muhammad Aamir
      Email: muhammad.aamir@ieee.org
      Image: /assets/images/trainers/trainer-muhammad-aamir.jpg
      Twitter: Muhammad__Aamir
      Biography: The trainer of this course is a cybersecurity certified professional i.e. Certified Information
        Systems Security Professional (CISSP) and Certified Ethical Hacker (CEH) with more than 12 years of work
        experience. He works in the field of cybersecurity for various domains such as cybersecurity research
        and threat intelligence, training for cybersecurity user awareness, cybersecurity policies/frameworks,
        and penetration testing. He has a passion of teaching and likes to share the knowledge obtained during
        job tasks. He has also conducted on premise classes as well as online sessions to deliver the lectures
        on Ethical Hacking to university students as visiting faculty.
      TrainerId: muhammad_aamir
  Title: Ethical Hacking for Beginners
  URL: /register/?id=sku_HOuDe84Hc1hBGm
  SectionId: sku_HOuDe84Hc1hBGm
  Description: "This course is based on Ethical Hacking also known as Penetration Testing. The hacking, when 
    done in ethical ways with the permission of the asset owner, turns out to be quite effective for 
    organizations to find out the vulnerabilities in their environment of information systems and enable them 
    to fix those weaknesses before malicious hackers or adversaries may exploit their systems. This kind of 
    hacking is classified as White Hat Hacking. This course is formulated to make the students aware of various 
    hacking tools being used in the industry by cybersecurity professionals. The methodology of the course 
    covers more than 90% practical hands-on approach.<br>
    Learning Outcomes: Students will be able to distinguish ethical hacking from malicious hacking knowing the 
    concepts of White Hat and Black Hat hacking. They will get hands-on knowledge to perform the hacking tasks 
    in ethical ways to improve the security of assets by using various hacking tools.<br>
    <strong>Resources for hands-on approach:</strong><br>
    <ol>
    <li>Attack side: Kali Linux 2020.x, NMAP, Metasploit Framework (MSF).</li>
    <li>Victim side: Metasploitable, MS Windows 10, OWASP Resources i.e. Damn Vulnerable Web Application (DVWA) and buggy Web Application (bWAPP).</li>
    </ol>
    Note: The above resources will be installed and organized in a virtual environment i.e. Oracle VM 
    Virtualbox."
